# Generated by Django 5.1.6 on 2026-01-07 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentToCourseOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=1)),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.coursecontent')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.courseoutcome')),
            ],
            options={
                'unique_together': {('course_content', 'course_outcome')},
            },
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course_outcomes',
            field=models.ManyToManyField(through='outcomes.ContentToCourseOutcome', to='outcomes.courseoutcome'),
        ),
        migrations.CreateModel(
            name='CourseToProgramOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=1)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.courseoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.programoutcome')),
            ],
            options={
                'unique_together': {('course_outcome', 'program_outcome')},
            },
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='program_outcomes',
            field=models.ManyToManyField(through='outcomes.CourseToProgramOutcome', to='outcomes.programoutcome'),
        ),
    ]
