# Generated by ChatGPT - add score field to CourseContent
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outcomes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
