# Generated by Django 4.2.23 on 2025-12-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_alter_learningoutcome_id_alter_programoutcome_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='programoutcome',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
