# Generated by ChatGPT - add StudentGrade model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outcomes", "0002_add_score_to_coursecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64, db_index=True)),
                ("score", models.FloatField()),
                (
                    "course_content",
                    models.ForeignKey(on_delete=models.CASCADE, to="outcomes.coursecontent"),
                ),
            ],
            options={
                "unique_together": {("student_id", "course_content")},
            },
        ),
    ]
