# Generated by Django 5.1.6 on 2025-11-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer', models.CharField(choices=[('course_content', 'course_content'), ('course_outcome', 'course_outcome'), ('program_outcome', 'program_outcome')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='giraph.node')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='giraph.node')),
            ],
        ),
    ]
