# Generated by Django 4.2.23 on 2025-12-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer', models.CharField(choices=[('course_content', 'course_content'), ('course_outcome', 'course_outcome'), ('program_outcome', 'program_outcome')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='giraph.node')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='giraph.node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('node1', 'node2'), name='unique_relation_pair'),
        ),
    ]
