# Generated by Django 5.1.6 on 2025-11-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giraph', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('node1', 'node2'), name='unique_relation_pair'),
        ),
    ]
