# Generated by Django 5.2.8 on 2025-12-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giraph', '0002_relation_unique_relation_pair'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='programs.program'),
        ),
    ]
