# Generated by assistant on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giraph', '0003_node_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
