# Generated by Django 5.2.8 on 2026-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giraph', '0004_add_score_to_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
