# Generated by Django 5.2.8 on 2026-01-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giraph', '0005_node_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='description',
        ),
    ]
