# Generated by Django 4.2.23 on 2025-12-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_department_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
